# Generated by Django 3.2 on 2023-05-03 15:39

import dj_site_accounts.sites_profiles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, verbose_name='Name')),
                ('description', models.JSONField(default=dict, verbose_name='Description')),
                ('address', models.JSONField(default=dict, verbose_name='Address')),
                ('copyrights', models.JSONField(default=dict, verbose_name='Copyrights')),
                ('keywords', models.JSONField(default=dict, verbose_name='Keywords')),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to=dj_site_accounts.sites_profiles.models.SiteProfile.upload_logo_to, verbose_name='Logo')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Sites Profiles',
                'default_permissions': (),
            },
        ),
    ]
